function show(spike_classes, spikes)
    classes = unique(spike_classes);
    for i=1:length(classes)
        class = classes(i);
        s = spikes(:,find(spike_classes==class));
        figure; hold on;
        for j=1:size(s,2)
            patchline((1:64)/24, s(:, j),'edgealpha',min(1,40.0/size(s, 2)));
        end
        hTitle = title(['Spike Class ', num2str(i)]);
        hXLabel = xlabel('Time (ms)');
        hYLabel = ylabel('Voltage (uV)');

        set( gca                       , ...
            'FontName'   , 'Helvetica' );
        set([hTitle, hXLabel, hYLabel], ...
            'FontName'   , 'AvantGarde');
        set([hXLabel, hYLabel]  , ...
            'FontSize'   , 10          );
        set( hTitle                    , ...
            'FontSize'   , 12          , ...
            'FontWeight' , 'bold'      );

        set(gca, ...
          'Box'         , 'off'     , ...
          'TickDir'     , 'out'     , ...
          'TickLength'  , [.02 .02] , ...
          'XMinorTick'  , 'on'      , ...
          'YMinorTick'  , 'on'      , ...
          'YGrid'       , 'off'      , ...
          'XColor'      , [.3 .3 .3], ...
          'YColor'      , [.3 .3 .3], ...
          'YTick'       , -5:.5:5, ...
          'LineWidth'   , 1         );
        set(gcf, 'PaperPositionMode', 'auto');
        print('-dpng', ['spikes',num2str(i),'.png']);
    end
    
    


	figure; hold on;
    hData1 = plot([1:size(spikes, 1)]/24, spikes(:,5), 'Color', [0 0 .8], 'LineWidth', .1);
    hData2 = plot([1:size(spikes, 1)]/24, spikes(:,6), 'Color', [.8 0 0], 'LineWidth', .1);
    hData3 = plot([1:size(spikes, 1)]/24, spikes(:,7), 'Color', [0 .8 0], 'LineWidth', .1);
    
    hTitle = title('Simulated Spike Data');
    hXLabel = xlabel('Time (ms)');
    hYLabel = ylabel('Voltage (uV)');

    legend('Spike class 1', 'Spike class 2', 'Spike class 3');

    set( gca                       , ...
        'FontName'   , 'Helvetica' );
    set([hTitle, hXLabel, hYLabel], ...
        'FontName'   , 'AvantGarde');
    set([hXLabel, hYLabel]  , ...
        'FontSize'   , 10          );
    set( hTitle                    , ...
        'FontSize'   , 12          , ...
        'FontWeight' , 'bold'      );

    set(gca, ...
      'Box'         , 'off'     , ...
      'TickDir'     , 'out'     , ...
      'TickLength'  , [.02 .02] , ...
      'XMinorTick'  , 'on'      , ...
      'YMinorTick'  , 'on'      , ...
      'YGrid'       , 'on'      , ...
      'XColor'      , [.3 .3 .3], ...
      'YColor'      , [.3 .3 .3], ...
      'YTick'       , -8:2:8, ...
      'LineWidth'   , 1         );
    set(gcf, 'PaperPositionMode', 'auto');
end