function Hd = leastSquaresFilt
%LEASTSQUARESFILT Returns a discrete-time filter object.

%
% MATLAB Code
% Generated by MATLAB(R) 7.14 and the DSP System Toolbox 8.2.
%
% Generated on: 26-Mar-2014 16:48:59
%

% FIR least-squares Bandpass filter designed using the FIRLS function.

% All frequency values are in Hz.
Fs = 24000;  % Sampling Frequency

N      = 18;    % Order
Fstop1 = 250;   % First Stopband Frequency
Fpass1 = 300;   % First Passband Frequency
Fpass2 = 3000;  % Second Passband Frequency
Fstop2 = 3300;  % Second Stopband Frequency
Wstop1 = 2;     % First Stopband Weight
Wpass  = 4;     % Passband Weight
Wstop2 = 5;     % Second Stopband Weight

% Calculate the coefficients using the FIRLS function.
b  = firls(N, [0 Fstop1 Fpass1 Fpass2 Fstop2 Fs/2]/(Fs/2), [0 0 1 1 0 ...
           0], [Wstop1 Wpass Wstop2]);
Hd = dfilt.dffir(b);

% [EOF]
