function Hd = least_squares_filter
%LEAST-SQUARES Returns a discrete-time filter object.

%
% MATLAB Code
% Generated by MATLAB(R) 7.14 and the Signal Processing Toolbox 6.17.
%
% Generated on: 25-Mar-2014 21:08:27
%

% FIR least-squares Bandpass filter designed using the FIRLS function.

% All frequency values are in Hz.
Fs = 24000;  % Sampling Frequency

N      = 20;     % Order
Fstop1 = 275;    % First Stopband Frequency
Fpass1 = 300;    % First Passband Frequency
Fpass2 = 1600;   % Second Passband Frequency
Fstop2 = 1800;   % Second Stopband Frequency
Wstop1 = 0.001;  % First Stopband Weight
Wpass  = 1;      % Passband Weight
Wstop2 = 0.001;  % Second Stopband Weight

% Calculate the coefficients using the FIRLS function.
b  = firls(N, [0 Fstop1 Fpass1 Fpass2 Fstop2 Fs/2]/(Fs/2), [0 0 1 1 0 ...
           0], [Wstop1 Wpass Wstop2]);
Hd = dfilt.dffir(b);

% [EOF]
